[package]
name = "altaria-examples"
version = "0.1.0"
edition = "2021"

[dependencies]
altaria={ path = "../", features = ["json", "logging"] }

tokio={ version = "1.42.0", features = ["full"] }
serde = { version = "1.0.216", features = ["derive"]}
serde_json = { version = "1.0.74" }