[package]
name = "altaria-examples"
version = "0.1.0"
edition = "2021"

[dependencies]
altaria={ path = "../" }
altaria-macros = { path = "../macros" }

tokio={ version = "1.42.0", features = ["full"] }
