[package]
name = "altaria"
version = "0.1.3"
edition = "2021"

description = "Altaria is an asynchronous, memory-safe, blazingly fast HTTP server written in Rust. It currently supports HTTP1.1 parsing and encoding and HTTP2 parsing."
authors = ["Gabriel <gabriel@minatel.dev>"]
license-file = "LICENSE"
homepage = "https://github.com/SrGaabriel/altaria"
repository = "https://github.com/SrGaabriel/altaria"

[dependencies]
tokio = { version = "1.42.0", features = ["full"] }
async-trait = "0.1.83"
chrono = "0.4.38"
hpack = "0.3.0"
anyhow = "1.0.94"
thiserror = "2.0.4"
altaria-macros = { path = "macros", version = "0.1.0" }